spring.application.name=estudio-musical-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/estudiomusical
spring.data.mongodb.auto-index-creation=true

# Server Configuration
server.port=8080

# Logging
logging.level.com.estudiomusical=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
